### ISSUE TITLE
[FE] 리팩토링

### ISSUE THREAD

**Issue by headring** [boostup-project/boostup-project#567]
## 📝 Github Issue
리팩토링

## 💫 Branch
feat/이슈요약#[이슈번호]
> ex) refactor/things#567

## ✔️ Check List
[UX]
- [x] 알림창(sweetalert2, react-toastify) #679
  - swal은 확인이 한 번 더 필요한 것에 적용(로그인 필요 기능, 삭제, 취소 등등)
  - 그 외는 toastify 적용 
 

[SEO]
- [x] (02.20) 메타데이터 작성  
#661  
#663  
#665 

[배포환경]
- [x] (02.10) 새로 고침 시 메인페이로 이동되는 문제 #597 
- [x] (02.18) Vercel을 이용한 SSR 배포 테스트 완료 #654  
- [x] (02.19) Route53을 이용하여 커스텀 도메인 연결, Daily Log 템플릿 활용하여 Vercel 사용 이유와 커스텀 도메인 연결방법 기록 #655 

[돈 단위/원화]
- [x] (02.09)아이콘 대신 원화 폰트 사용, 컬러 및 화면 표시내역 통일

[검색창]
- [x] 검색창 모바일 사이즈 조정 및 다른 route 이동 시 꺼짐

[매인페이지]
- [x] (02.11) 카드 글자 배경 흰색으로 변경 및 이미지 클릭 시에도 상세페이지 이동 onClick

[상세페이지]
- [x] 모바일 상세페이지 DB이미지로 대체
- [x] (02.09)수정 후 re-rendering 적용
- [x] (02.10) 이미지 클릭 시 모달  
- [x] (02.11) 추가정보의 수업료 문자열 데이터로 `toLocalString` 삭제  
- [x] (02.11) 참고사진 border 삭제 및 참고사진과 popup 사진 upsize 

[마이페이지]
- [x] (02.09)유저 정보 수정 시 데이터 re-rendering
- [x] (02.11)프로필 이미지 border 삭제

[모바일 필터]
- [x] 모바일 언어 필터 z-index 1 설정
- [x] map에서 불필요 최상위 태그 삭제하여 key값 에러 해결

[모달]
- [x] 글작성 모달 제출 이후 invalidateQuery로 re-rendering
- [x] 글작성 & 수정 모달 : 재직회사 500글자, 진행방식 1000글자 #679 

[로그아웃]
- [x] (02.11) 로그아웃 통신으로 토큰 삭제 완료(현재 refresh가 필수라서 랜덤 문자열 넣어서 통신중)

[결제]
- [x] (02.09)결제수단 아이콘 추가
